### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference"  when running for the first time

### ISSUE THREAD

**Issue by saputkin** [lavalamp-/ipv666#89]
Hello,
i'm trying to use your cool tool for the first time,
i followed the installation instruction and everything was fine, then when running 666scan for the first time i get the following error
![image](https://user-images.githubusercontent.com/40404616/49929960-56551480-fecc-11e8-9ac7-4c557a1cdf34.png)

**Comment by toobus** [comment]
Hello lavalamp-,
I'd just like to second saputkin's report above.. this is using go 1.11.4 to build.. build looked ok

![image](https://user-images.githubusercontent.com/17363866/50842312-07b06400-132c-11e9-8557-82a3f4d172db.png)

**Comment by lavalamp-** [comment]
Thanks @toobus! We're looking into this today and should have a fix out within the next week.

**Comment by lavalamp-** [comment]
The culprit was attempting to delete files in the `bloom` directory before making a call to `initFilesystem`. This should be fixed in https://github.com/lavalamp-/ipv666/commit/e3456e9820adf6bd3a6bf91d447f50edcb454542.
